// src/components/Abilities.jsx
import React from 'react'
import PropTypes from 'prop-types'

export const Abilities = (props) => {
  return (
    <div className="card blue-grey darken-1">
      <div className="card-content white-text">
        <span className="card-title orange-text">
          Abilities
        </span>
        <p><b>Race</b></p>
        <ul className="normal-ul push-right">
          { props.abilities.race.map(a => <li key={a}>{ a }</li>) }
        </ul>
        <p><b>Class</b></p>
        <ul className="normal-ul push-right">
          { props.abilities.class.map(a => <li key={a}>{ a }</li>) }
        </ul>
        <p><b>Feats</b></p>
        <ul className="normal-ul push-right">
          { props.abilities.feats.map(a => <li key={a}>{ a }</li>) }
        </ul>
      </div>
    </div>
  )
}

Abilities.propTypes = {
  abilities: PropTypes.object.isRequired
}

// src/components/Abilities.vue
<template>
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title orange-text">
        <i class="material-icons small">collections</i>
        Abilities
      </span>
      <p><b>Race</b></p>
      <ul class="normal-ul push-right">
        <li v-for="(ability, index) in abilities.race" :key="index">{{ ability }}</li>
      </ul>
      <p><b>Class</b></p>
      <ul class="normal-ul push-right">
        <li v-for="(ability, index) in abilities.class" :key="index">{{ ability }}</li>
      </ul>
      <p><b>Feats</b></p>
      <ul class="normal-ul push-right">
        <li v-for="(ability, index) in abilities.feats" :key="index">{{ ability }}</li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    abilities: {
      type: Object,
      required: true
    }
  }
}
</script>
