// src/components/Background.jsx
import React from 'react'
import PropTypes from 'prop-types'

export const Background = (props) => {
  return (
    <div className="card blue-grey darken-1">
      <div className="card-content white-text">
        <span className="card-title orange-text">
          Background
        </span>
        <p><b>{ props.background.choice }</b></p><br />
        { props.background.quotes.map(q => <p key={q}>{ q }</p>) }
        <br />
        <p><b>Languages</b></p>
        <ul className="normal-ul push-right">
          { props.languages.map(l => <p key={l}>{ l }</p>) }
        </ul>
      </div>
    </div>
  )
}

Background.propTypes = {
  background: PropTypes.object.isRequired,
  languages: PropTypes.array.isRequired
}

// src/components/Background.vue
<template>
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title orange-text">
        <i class="material-icons small">art_track</i>
        Background
      </span>
      <p><b>{{ background.choice }}</b></p><br />
      <p v-for="(quote, index) in background.quotes" :key="index">"{{ quote }}"</p>
      <br />
      <p><b>Languages</b></p>
      <ul class="normal-ul push-right">
        <li v-for="(language, index) in languages" :key="index">{{ language }}</li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    background: {
      type: Object,
      required: true
    },
    languages: {
      type: Array,
      required: true
    }
  }
}
</script>
