// src/components/Equipment.vue
<template>
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title orange-text">
        <i class="material-icons small">business_center</i>
        Equipment
      </span>
      <p><b>Gold</b>: {{ equipment.gold }}</p>
      <ul class="normal-ul push-right">
        <li v-for="(item, index) in equipment.items" :key="index">{{ item }}</li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    equipment: {
      type: Object,
      required: true
    }
  }
}
</script>

// src/components/Equipment.jsx
import React from 'react'
import PropTypes from 'prop-types'

export const Equipment = (props) => {
  return (
    <div className="card blue-grey darken-1">
      <div className="card-content white-text">
        <span className="card-title orange-text">
          Equipment
        </span>
        <p><b>Gold</b>: { props.equipment.gold }</p>
        <ul className="normal-ul push-right">
          { props.equipment.items.map(i => <p key={i}>{ i }</p>) }
        </ul>
      </div>
    </div>
  )
}

Equipment.propTypes = {
  equipment: PropTypes.object.isRequired
}
