// src/components/LifeEvents.vue
<template>
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title orange-text">
        <i class="material-icons small">child_care</i>
        Life Events
      </span>
      <ul class="normal-ul push-right">
        <li v-for="(event, index) in lifeEvents" :key="index">{{ event }}</li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    lifeEvents: {
      type: Array,
      required: true
    }
  }
}
</script>

// src/components/LifeEvents.jsx
import React from 'react'
import PropTypes from 'prop-types'

export const LifeEvents = (props) => {
  return (
    <div className="card blue-grey darken-1">
      <div className="card-content white-text">
        <span className="card-title orange-text">
          Life Events
        </span>
        <ul className="normal-ul push-right">
          { props.lifeEvents.map(e => <p key={e}>{ e }</p>) }
        </ul>
      </div>
    </div>
  )
}

LifeEvents.propTypes = {
  lifeEvents: PropTypes.array.isRequired
}
