// src/components/Overview.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { proficiencyBonus } from '../systemRules.js'

export const Overview = (props) => {
  return (
    <div className="card blue-grey darken-1">
      <div className="card-content white-text">
        <span className="card-title orange-text">
          Overview
        </span>
        <table className="table">
          <tbody>
            <tr>
              <th>Name</th>
              <td>{ props.overview.name }</td>
            </tr>
            <tr>
              <th>Race</th>
              <td>{ props.overview.race }</td>
            </tr>
            <tr>
              <th>Class</th>
              <td>{ props.overview.class }</td>
            </tr>
            <tr>
              <th>Level</th>
              <td>{ props.overview.level }</td>
            </tr>
            <tr>
              <th>Prof. Bonus</th>
              <td>{ `+${proficiencyBonus(props.overview.level)}` }</td>
            </tr>
            <tr>
              <th>Max Health</th>
              <td>{ props.overview.maxHealth }</td>
            </tr>
            <tr>
              <th>Hit Die</th>
              <td>{ props.overview.hitDie }</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  )
}

Overview.propTypes = {
  overview: PropTypes.object.isRequired
}

// src/components/Overview.vue
<template>
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title orange-text">
        <i class="material-icons small">account_circle</i>
        Overview
      </span>
      <table class="table">
        <tbody>
          <tr>
            <th>Name</th>
            <td>{{ overview.name }}</td>
          </tr>
          <tr>
            <th>Race</th>
            <td>{{ overview.race }}</td>
          </tr>
          <tr>
            <th>Class</th>
            <td>{{ overview.class }}</td>
          </tr>
          <tr>
            <th>Level</th>
            <td>{{ overview.level }}</td>
          </tr>
          <tr>
            <th>Prof. Bonus</th>
            <td>{{ proficiencyBonus() }}</td>
          </tr>
          <tr>
            <th>Max Health</th>
            <td>{{ overview.maxHealth }}</td>
          </tr>
          <tr>
            <th>Hit Die</th>
            <td>{{ overview.hitDie }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import { proficiencyBonus } from '@/systemRules'

export default {
  props: {
    overview: {
      type: Object,
      required: true
    }
  },
  methods: {
    proficiencyBonus () {
      const bonus = proficiencyBonus(this.overview.level)
      return `+${bonus}`
    }
  }
}
</script>
