// src/components/Sheet.jsx
import React from 'react'
import PropTypes from 'prop-types'

import { Overview } from './Overview.jsx'
import { Background } from './Background.jsx'
import { Attributes } from './Attributes.jsx'
import { Skills } from './Skills.jsx'
import { Equipment } from './Equipment.jsx'
import { Abilities } from './Abilities.jsx'
import { Spells } from './Spells.jsx'
import { LifeEvents } from './LifeEvents.jsx'

export const Sheet = (props) => {
  return (
    <div>
      <div className="row">
        <div className="col s12 m6">
          <Overview overview={props.characterData.overview} />
        </div>
        <div className="col s12 m6">
          <Background background={props.characterData.background} languages={props.characterData.languages} />
        </div>
      </div>
      <div className="row">
        <div className="col s12 m6">
          <Attributes attributes={props.characterData.attributes} saves={props.characterData.saves} />
        </div>
        <div className="col s12 m6">
          <Skills skills={props.characterData.skills} />
        </div>
      </div>
      <div className="row">
        <div className="col s12 m6">
          <Equipment equipment={props.characterData.equipment} />
        </div>
        <div className="col s12 m6">
          <Abilities abilities={props.characterData.abilities} />
        </div>
      </div>
      <div className="row">
        <div className="col s12">
          <Spells spells={props.characterData.spells} casting={props.characterData.casting} />
        </div>
      </div>
      <div className="row">
        <div className="col s12">
          <LifeEvents lifeEvents={props.characterData.lifeEvents} />
        </div>
      </div>
    </div>
  )
}

Sheet.propTypes = {
  characterData: PropTypes.object.isRequired
}

// src/components/Sheet.vue
<template>
  <div id="character_sheet">
    <div class="row">
      <div class="col s12 m6">
        <Overview :overview="characterData.overview" />
      </div>
      <div class="col s12 m6">
        <Background :background="characterData.background" :languages="characterData.languages" />
      </div>
    </div>
    <div class="row">
      <div class="col s12 m6">
        <Attributes :attributes="characterData.attributes" :saves="characterData.saves" />
      </div>
      <div class="col s12 m6">
        <Skills :skills="characterData.skills" />
      </div>
    </div>
    <div class="row">
      <div class="col s12 m6">
        <Equipment :equipment="characterData.equipment" />
      </div>
      <div class="col s12 m6">
        <Abilities :abilities="characterData.abilities" />
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <Spells :spells="characterData.spells" :casting="characterData.casting" />
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <LifeEvents :lifeEvents="characterData.lifeEvents" />
      </div>
    </div>
  </div>
</template>

<script>
import Overview from '@/components/Overview'
import Background from '@/components/Background'
import Attributes from '@/components/Attributes'
import Skills from '@/components/Skills'
import Equipment from '@/components/Equipment'
import Abilities from '@/components/Abilities'
import Spells from '@/components/Spells'
import LifeEvents from '@/components/LifeEvents'

export default {
  components: {
    Overview,
    Background,
    Attributes,
    Skills,
    Equipment,
    Abilities,
    Spells,
    LifeEvents
  },
  props: {
    characterData: {
      type: Object,
      required: true
    }
  }
}
</script>
